package com.lib.mylibrary.core.util

object Constants {

    const val MALL_ID = "mall_1"
    const val BASE_URL = "https://asgard-apis-stage.frt.one/"
    const val AUTH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Inp5aGVlakZpYVpHc2YzeEFINktVY1EkJCIsImZpcnN0TmFtZSI6Ik5pa3VuaiIsImxhc3ROYW1lIjoiQWdnYXJ3YWwiLCJlbWFpbCI6bnVsbCwibW9iaWxlTnVtYmVyIjo5ODEwMjEwNjE2LCJkZXZpY2UiOiIyIiwiZGV2aWNlSWQiOiJ6eGN2Ym5tcWFzZGYiLCJidWlsZCI6ImFzZGZnaHFzeGRjZnZnYiIsInByZWZlcnJlZE1hbGxJZCI6NiwiaXNFeGNsdXNpdmUiOjAsIndoYXRzQXBwQ29uY2VudCI6IiIsIm9wdGVkRm9yRGVsZXRpb24iOjAsInJlYWN0aXZhdGlvbkNvZGUiOm51bGwsInByb2ZpbGVQaWMiOiJodHRwczovL3B1YmxpYy1mdXR1cmVyZXRhaWwtZGF0YS5zMy5hbWF6b25hd3MuY29tL3Byb2ZpbGVQaWMvODk4MDMwMDY1MzktMS0yMDIwLTgtMjYucG5nIiwibGFzdExvZ2luIjoiMzAtMDUtMjAyMiIsImRlbGV0aW9uUmVxdWVzdGVkQXQiOm51bGwsImlhdCI6MTY1NDA4NDQyOSwiZXhwIjoxNjU1MzgwNDI5fQ.YUP0ilrkd0IBxWpXophZEd6KioeIihZyolWS8DBOLF0"
    const val IDEAL_PAGE_SIZE = 20
}