package com.lib.mylibrary.ui.feature_loyalty_home.presentation

object LoyaltyHubHomeColors {

    var SCREEN_TITLE_TEXT_COLOR = "#693C14"
    var BACKGROUND_COLOR = "#FCFBF6"
    var FEATURE_CARD_BG_COLOR = "#F2EDD9"
    var FEATURE_CARD_BORDER_COLOR = "#E8C653"
    var FEATURE_CARD_CTA_COLOR = "#E8C653"
    var FEATURE_CARD_TITLE_TEXT_COLOR = "#693C14"
    var FEATURE_CARD_SUB_TEXT_COLOR = "#000000"
    var FEATURE_CARD_CTA_TEXT_COLOR = "#1B1005"
    var POINTS_CARD_VALUE_TEXT_COLOR = "#693C14"
    var GEMS_CARD_VALUE_TEXT_COLOR = "#693C14"
    var TIER_CARD_VALUE_TEXT_COLOR = "#693C14"
    var POINTS_CURRENCY_TEXT_COLOR = "#1B1005"
    var GEMS_CURRENCY_TEXT_COLOR = "#1B1005"
    var TIER_CURRENCY_TEXT_COLOR = "#1B1005"
}